# Generated by Django 3.1.6 on 2021-02-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='size',
            field=models.IntegerField(),
        ),
    ]
