# Generated by Django 3.1.6 on 2021-02-11 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210211_1838'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PropertyAmenities',
            new_name='PropertyAmenity',
        ),
    ]
